/*
 * Leisound V1 Board Pin Definitions — DEPRECATED backward-compat shim
 *
 * The board has been re-identified as "NomadCast V1". The single source of
 * truth is now boards/esp32s3/nomadcast_v1.h (NOMADCAST_* macros).
 *
 * This header keeps the old LEISOUND_* names working so existing includes
 * (board.h, system/input) don't break. New code should use nomadcast_v1.h.
 */

#ifndef LEISOUND_V1_H
#define LEISOUND_V1_H

#include "nomadcast_v1.h"

/* ---- Power ---- */
#define LEISOUND_PIN_AP_POWER        NOMADCAST_PIN_AP_POWER
#define LEISOUND_PIN_LCD_POWER       NOMADCAST_PIN_LCD_POWER

/* ---- SPI2 LCD ---- */
#define LEISOUND_LCD_HOST            NOMADCAST_LCD_HOST
#define LEISOUND_LCD_H_RES           NOMADCAST_LCD_H_RES
#define LEISOUND_LCD_V_RES           NOMADCAST_LCD_V_RES
#define LEISOUND_LCD_BIT_PER_PIXEL   NOMADCAST_LCD_BIT_PER_PIXEL
#define LEISOUND_PIN_LCD_CS          NOMADCAST_PIN_LCD_CS
#define LEISOUND_PIN_LCD_DC          NOMADCAST_PIN_LCD_DC
#define LEISOUND_PIN_LCD_RST         NOMADCAST_PIN_LCD_RST
#define LEISOUND_PIN_LCD_BL          NOMADCAST_PIN_LCD_BL
#define LEISOUND_PIN_SPI_SCK         NOMADCAST_PIN_SPI_SCK
#define LEISOUND_PIN_SPI_MOSI        NOMADCAST_PIN_SPI_MOSI
#define LEISOUND_PIN_SPI_MISO        NOMADCAST_PIN_SPI_MISO

/* ---- Touch I2C ---- */
#define LEISOUND_PIN_I2C_SDA         NOMADCAST_PIN_I2C_SDA
#define LEISOUND_PIN_I2C_SCL         NOMADCAST_PIN_I2C_SCL
#define LEISOUND_PIN_TP_INT          NOMADCAST_PIN_TP_INT
#define LEISOUND_PIN_TP_RST          NOMADCAST_PIN_TP_RST
#define LEISOUND_GT911_ADDR_1        NOMADCAST_GT911_ADDR_1
#define LEISOUND_GT911_ADDR_2        NOMADCAST_GT911_ADDR_2

/* ---- LVGL ---- */
#define LEISOUND_LVGL_BUF_HEIGHT       NOMADCAST_LVGL_BUF_HEIGHT
#define LEISOUND_LVGL_TICK_PERIOD_MS   NOMADCAST_LVGL_TICK_PERIOD_MS
#define LEISOUND_LVGL_TASK_MAX_DELAY   NOMADCAST_LVGL_TASK_MAX_DELAY
#define LEISOUND_LVGL_TASK_MIN_DELAY   NOMADCAST_LVGL_TASK_MIN_DELAY
#define LEISOUND_LVGL_TASK_STACK       NOMADCAST_LVGL_TASK_STACK
#define LEISOUND_LVGL_TASK_PRIORITY    NOMADCAST_LVGL_TASK_PRIORITY

/* ---- Audio I2S / amp ---- */
#define LEISOUND_PIN_I2S_MCLK        NOMADCAST_PIN_I2S_MCLK
#define LEISOUND_PIN_I2S_BCLK        NOMADCAST_PIN_I2S_BCLK
#define LEISOUND_PIN_I2S_WS          NOMADCAST_PIN_I2S_WS
#define LEISOUND_PIN_I2S_DOUT        NOMADCAST_PIN_I2S_DOUT
#define LEISOUND_PIN_I2S_DIN         NOMADCAST_PIN_I2S_DIN
#define LEISOUND_PIN_AMP_EN          NOMADCAST_PIN_AMP_EN

/* ---- Battery ---- */
#define LEISOUND_BAT_ADC_UNIT        NOMADCAST_BAT_ADC_UNIT
#define LEISOUND_BAT_ADC_CHANNEL     NOMADCAST_BAT_ADC_CHANNEL
#define LEISOUND_BAT_CHG_PIN         NOMADCAST_BAT_CHG_PIN

/* ---- Keys ---- */
#define LEISOUND_PIN_KEY_VOL_DOWN    NOMADCAST_PIN_KEY_VOL_DOWN
#define LEISOUND_PIN_KEY_VOL_UP      NOMADCAST_PIN_KEY_VOL_UP
#define LEISOUND_PIN_KEY_STOP        NOMADCAST_PIN_KEY_STOP
#define LEISOUND_PIN_KEY_POWER       NOMADCAST_PIN_KEY_POWER

#endif /* LEISOUND_V1_H */
