idf_component_register(
    SRCS
        "framework/page_navigator.c"
        "widgets/lv_page.c"
        "widgets/lv_status_bar.c"
        "widgets/lv_toast.c"
        "widgets/lv_bottom_sheet.c"
        "widgets/lv_num_input.c"
        "imgs/24x24/ic_timer.c"
        "imgs/24x24/ic_downloading.c"
        "imgs/24x24/ic_wifi.c"
        "imgs/24x24/ic_battery_android_0.c"
        "imgs/24x24/ic_battery_android_1.c"
        "imgs/24x24/ic_battery_android_2.c"
        "imgs/24x24/ic_battery_android_3.c"
        "imgs/24x24/ic_battery_android_4.c"
        "imgs/24x24/ic_battery_android_5.c"
        "imgs/24x24/ic_battery_android_6.c"
        "imgs/24x24/ic_battery_android_full.c"
        "imgs/24x24/ic_battery_android_bolt.c"
        "imgs/24x24/ic_search.c"
        "imgs/24x24/ic_forward_media.c"
        "imgs/24x24/ic_info.c"
        "imgs/24x24/ic_login.c"
        "imgs/24x24/ic_logout.c"
        "imgs/24x24/ic_podcasts.c"
        "imgs/24x24/ic_settings.c"
        "fonts/font_harmony.c"
        "imgs/40x40/ic_settings_40x40.c"
        "imgs/40x40/ic_podcasts_40x40.c"
        "imgs/16x16/ic_schedule_16x16.c"
        "imgs/16x16/ic_stacks_16x16.c"
    INCLUDE_DIRS "framework" "widgets" "imgs/24x24" "imgs/40x40" "imgs/16x16"
    REQUIRES lvgl clock events logs
)
